# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_alm', models.CharField(max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art', models.CharField(max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('stock_actual', models.PositiveIntegerField(default=b'0', verbose_name=b'Stock Actual')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Almacen')),
            ],
            options={
                'permissions': (('ver_detalle_articulo', ' Can detail articulo'),),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cat', models.CharField(max_length=50, null=True, unique=True, verbose_name=b'Codigo')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_u', models.FloatField()),
                ('precio_t', models.FloatField()),
                ('observacion', models.TextField(blank=True)),
                ('fecha_i', models.DateTimeField(auto_now_add=True)),
                ('factura', models.IntegerField(unique=True)),
                ('salida', models.IntegerField(null=True)),
                ('saldo', models.IntegerField(null=True)),
                ('total_i', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Articulo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado', verbose_name=b'Funcionario')),
            ],
            options={
                'ordering': ['fecha_i'],
                'verbose_name_plural': 'Ingresos',
                'permissions': (('ver_detalle_ingreso', 'Can detail ingreso'),),
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField(null=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_s', models.DateTimeField(auto_now_add=True)),
                ('total_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.Articulo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Empleado', verbose_name=b'Funcionario')),
            ],
            options={
                'ordering': ['fecha_s'],
                'permissions': (('ver_detalle_salida', ' Can detail salida'),),
            },
        ),
        migrations.CreateModel(
            name='Tipo_Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.Tipo_Medida'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
