# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[(b'', b'Seleccione Genero'), (b'Masculino', b'Masculino'), (b'Femenino', b'Femenino')], max_length=15)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'permissions': (('ver_detalle_proveedor', 'Can detail proveedor'),),
            },
        ),
    ]
