# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import empleado.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name=b'Nombre de Unidad')),
            ],
            options={
                'ordering': ['descripcion'],
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.PositiveIntegerField(unique=True, validators=[empleado.models.validate_ci])),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[(b'', b'Selecione    Cargo '), (b'Auditor (a)', b'Auditor (a)'), (b'Cotizador (a)', b'Cotizador (a)'), (b'Contador (a)', b'Contador (a)'), (b'Enc. Almacenes', b'Enc. Almacenes'), (b'Enc. Area Tecnica', b'Enc. Area Tecnica'), (b'Enc. Bienes', b'Enc. Bienes'), (b'Enc. R. Humanos ', b'Enc. R. Humanos '), (b'Enc. Tesoreria', b'Enc. Tesoreria'), (b'Enc. Soldaduria', b'Enc. Soldaduria'), (b'Gerente General', b'Gerente General'), (b'Ing. de Sistemas', b'Ing. de Sistemas'), (b'Mecanico', b'Mecanico'), (b'Resp. Archivos', b'Resp. Archivos'), (b'Secretaria', b'Secretaria'), (b'Supervisor', b'Supervisor')], max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.Departamento')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'permissions': (('ver_detalle_empleado', 'Can detail empleado'),),
            },
        ),
    ]
